# Generated by Django 4.2.2 on 2024-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_desc",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterModelTable(
            name="user",
            table="tb_users",
        ),
    ]
